POST /testDB/update HTTP/1.1
Authorization: Basic YWRtaW46YWRtaW4=
Host: localhost:5820
User-Agent: spray-can/1.3.3
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 859

update=%0A%0APREFIX+agnos%3A+%3Chttp%3A%2F%2Fdata.agnos.ai%2Fresource%2F%3E%0APREFIX+dc%3A+%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Felements%2F1.1%2F%3E%0APREFIX+foaf%3A+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0APREFIX+owl%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0APREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX+skos%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%3E%0APREFIX+terms%3A+%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0APREFIX+time%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2006%2Ftime%23%3E%0APREFIX+xsd%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0AINSERT+DATA+%7B%0D%0A++GRAPH+%3Curn%3Atest%3Aagnos%3Adata%3E+%7B%0D%0A++++%3Curn%3Atest%3Awhatever%3E+foaf%3AgivenName+%22Bill%22%0D%0A++%7D%0D%0A%7D%0A++
